//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int cod_empleado { get; set; }
        public string nom_empleado { get; set; }
        public int edad_empleado { get; set; }
        public string sexo_empledo { get; set; }
        public decimal sueldo_empl { get; set; }
    }
}
